### ISSUE TITLE
Details for `externs` option flag

### ISSUE THREAD

**Issue by viebel** [google/closure-compiler-js#21] opened 2016-09-08 16:43 UTC
What is the format of the `externs` option flag?

I've tried a couple but nothing worked:

```javascript
var the_flags = {
  externs: ['cljs.user.foo = function(){};'],
  compilationLevel: "ADVANCED", 
  jsCode: [{src: 'var a = cljs.user.foo();console.log(a);'}]
};
var the_out = compile(the_flags);
console.info(the_out); 
```

```javascript
var the_flags = {
  externs: [{src:'cljs.user.foo = function(){};'}],
  compilationLevel: "ADVANCED",
  jsCode: [{src: 'var a = cljs.user.foo();console.log(a);'}]
};
var the_out = compile(the_flags);
console.info(the_out); 
```

In any case, the `compiledCode` is:

```javascript
 "var a=cljs.b.a();console.log(a);"
```

**Comment by viebel** [comment] 2016-09-13 12:52
Anyone could help here?

**Comment by viebel** [comment] 2016-09-13 12:52
maybe @samthor ?

**Comment by samthor** [comment] 2016-09-13 13:33
Please set `warningLevel: 'VERBOSE'` and you'll get more output to see what might be going wrong.

The latter is correct re: `src`, as per the README. The issue is that Closure doesn't know what `cljs.user` is. So you can try-

```js
var cljs;
cljs.user = {};
cljs.user.foo = function(){};
```

**Comment by samthor** [comment] 2016-09-13 13:34
I'll also add that this is not a Closure Compiler in JS specific issue, so I'm going to close this. Externs are a complex part of Closure. For more information check out [the official tutorial](https://developers.google.com/closure/compiler/docs/api-tutorial3#externs) or the [wiki](https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries).

**Closed by samthor** 2016-09-13 13:34 UTC

**Comment by thelgevold** [comment] 2016-12-01 06:14
I think you have to declare the root variable in the extern as well.

Something like this, perhaps:

`externs: ['var cljs; cljs.user.foo = function(){};']`
