### ISSUE TITLE
Does closure-compiler-js source map compatible with Rollup?

### ISSUE THREAD

**Issue by camelaissani** [google/closure-compiler-js#25] opened 2016-09-21 21:40 UTC
I try to write a Rollup plugin with closure-compiler-js: [rollup-plugin-closure-compiler-js](https://github.com/camelaissani/rollup-plugin-closure-compiler-js)

It seems that source map generated by closure-compiler is not compatible with Rollup.
I reproduce the issue in an [unit test](https://github.com/camelaissani/rollup-plugin-closure-compiler-js/blob/master/test/test.js#L42)
Here the link to the [CI build](https://travis-ci.org/camelaissani/rollup-plugin-closure-compiler-js#L168)

Should I transform the source map to make it compatible with Rollup? Or do I need to set specific options [here](https://github.com/camelaissani/rollup-plugin-closure-compiler-js/blob/master/src/index.js#L7)?

**Comment by Dominator008** [comment] 2016-09-21 22:22
ccing @ChadKillingsWorth in case he knows off the top of his head :)

**Comment by ChadKillingsworth** [comment] 2016-09-21 22:35
I'm guessing this is due to the fact that prior to this last month, Closure-compiler did not compose source maps. Changes are now merged to allow that, but it requires passing input sourcemaps to the compiler.

For the Java version gulp plugin, I compose the sourcemap manually after compilation. See https://github.com/ChadKillingsworth/closure-compiler-npm/blob/c03707e59fb7da90ae910da7c02ea68b4030714f/lib/gulp/index.js#L177-L193

Other reasons might be due to the paths or the `file` field of the source map not being correct.

On a related note, I'd love for you to add your rollup plugin directly to the java version at https://github.com/ChadKillingsworth/closure-compiler-npm. I would definitely review and approve such a PR. I've found that developers wish to manage the compiler version directly, so it makes npm version management so much easier if the plugins are hosted in the same repo.

**Comment by camelaissani** [comment] 2016-09-22 17:21
@ChadKillingsworth @Dominator008 thanks for your help. I'm gonna digging into your code to understand the source maps composition.

Once I've fixed the issue I would be happy to contribute to your project!

**Comment by camelaissani** [comment] 2016-09-25 17:05
I think closure-compiler works correctly. I would say that Rollup has a problem, but I am not 100% sure.
Here the issue open to the Rollup project: https://github.com/rollup/rollup/issues/961
there are all the details in my last comment.

**Comment by ChadKillingsworth** [comment] 2016-09-26 12:11
Looking at the stack trace, it seems to be caused due to the fact that the source map sources array has no valid source files rollup can locate. My guess is that `Input_0` should be the filename that rollup expects.

@samthor Thoughts on specifying the input filename for source maps? It could always be done post-processing too.

**Comment by samthor** [comment] 2016-09-26 12:18
I'm on my phone so I don't have the whole context. However, the generated
source map has no name: it has a blank filename, since the generated source
is also unnamed and (right now) always a single file. It should be
trivially renamable. We could do it inside the compiler at some point.

**Comment by ChadKillingsworth** [comment] 2016-09-26 12:19
@samthor The issue is the input filename for the sources array - that's a little bit harder (though still doable):

```json
"sources":[" [synthetic:base] "," [synthetic:util/global] ","Input_0"]
```

**Comment by camelaissani** [comment] 2016-09-26 14:15
@ChadKillingsworth @samthor So far, in my tests, only es6 getters have produced this error in Rollup.
I would say there is also another problem?

**Comment by ChadKillingsworth** [comment] 2016-09-26 14:56
I'm guessing it's caused due to the synthetic sources. You can try post processing the source map - specifically fill in the correct filename for the source `Input_0` and try setting the synthetic sources to `null`. 

I believe the issue comes from https://github.com/rollup/rollup/blob/c5d9d347721ad3d168b2ca6df27894be69815d1c/src/utils/collapseSourcemaps.js#L90

**Comment by GGG-KILLER** [comment] 2016-12-08 13:31
Wouldn't the problem be in fact that [rollup expects `module.originalSourceMap` to be `null`](https://github.com/rollup/rollup/blob/c5d9d347721ad3d168b2ca6df27894be69815d1c/src/utils/collapseSourcemaps.js#L106-L108) when the files are generated in memory, and that when value is anything other than that, it tries to [resolve all sources to filenames within the filesystem](https://github.com/rollup/rollup/blob/c5d9d347721ad3d168b2ca6df27894be69815d1c/src/utils/collapseSourcemaps.js#L120-L122)?

**Comment by ChadKillingsworth** [comment] 2018-06-21 20:38
I'd like to replace the `[ synthetic` source map references with some sort of real file path. But that issue needs addressed at https://github.com/google/closure-compiler

**Closed by ChadKillingsworth** 2018-06-21 20:38 UTC
