### ISSUE TITLE
Setting ECMASCRIPT_2017 for the languageOut option always errors

### ISSUE THREAD

**Issue by philipwalton** [google/closure-compiler-js#77] opened 2017-09-07 21:59 UTC
For example, even given the following reduced example, I get an error:

```js
const closureFlags = {
  jsCode: [{
    src: 'console.log(`foo`)',
    path: 'foo.js',
  }],
  languageIn: 'ECMASCRIPT_2017',
  languageOut: 'ECMASCRIPT_2017',
  compilationLevel: 'ADVANCED',
  warningLevel: 'VERBOSE',
};
```

I get the error `ReferenceError: window is not defined`:

```
ReferenceError: window is not defined
    at NFe (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:5715:29)
    at CFe (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:6430:228)
    at GFe (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:3360:65)
    at KFe (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:1417:19)
    at AIc (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:7403:54)
    at BIc.CIc [as fg] (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:7823:318365)
    at qIc (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:5741:146)
    at cEb (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:5083:91)
    at eFb (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:3416:69)
    at bGb.cGb [as $h] (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:7823:153996)
    at qGb (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:4710:36)
    at eEb (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:7201:153)
    at Ccd (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:7440:358)
    at aJ (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:1782:29)
    at dJ (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:3102:44)
    at /Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/jscomp.js:3289:46
    at module.exports (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/google-closure-compiler-js/compile.js:31:15)
```

I'm using version `20170806.0.0`, and note that I do NOT get this error when using the Java version.

(possibly related to #74, but I can't be sure since that issue gives no details)

**Comment by thomaspink** [comment] 2017-09-20 10:05
same here, also with `ECMASCRIPT6` as `languageOut`

**Comment by MatrixFrog** [comment] 2017-09-20 17:31
@tadeegan can you help us get a non-obfuscated stack trace?

**Comment by samthor** [comment] 2017-09-21 06:01
Inside the (newer version) of JSComp, there's a dangerous-looking line on 5772:

```js
function MIe(a){var b,c,d;b=window.console?new eJe:null;if(!b){return}fIe();if(lKe>a.a.Bo()){return}c=(d=a.     a.Bo(),d>=1000?'error':d>=900?'warn':d>=800?'info':'log');dJe(c,a.b)}
```

Which would predispose the existence of `window`.

**Comment by tadeegan** [comment] 2017-09-21 08:27
Why is the node version of the compiler built with obfuscation? It should
be built with all optimizations off since you're not optimizing for web. It
will make debugging these things a lot easier.

@tyler You can try tracing back the stack trace by hand in the sourcemap to
see where the original stack frames come from. We have an automated tool
for this which I can try when I get back from vacation. You can ask Daniel
about it.

**Comment by MatrixFrog** [comment] 2017-09-21 16:51
Code size and optimization matters (somewhat) for node too. You aren't downloading all the code into your browser but you still have to read and parse it all. Maybe for node we can enable some basic optimizations but turn off renaming.

**Comment by tadeegan** [comment] 2017-09-21 17:43
I'd like to see numbers for that. V8 has pretty good startup time. The jit
can do the same inlining as gwt optimization.

**Comment by gkdn** [comment] 2017-09-21 22:52
GWT's StackTraceDeobfuscator could be used for deobfuscation but it needs some plumbing that might not be trivial for non-web apps.

If it is very unlikely you will get same level performance with jitting that the GWT optimizations provides . On the other hand, you can just disable obfuscation (--style PRETTY) while keeping optimizations on; that might be a reasonable tradeoff.

**Comment by samthor** [comment] 2017-09-24 22:39
I've pushed a temporary fix in 20170910.0.1—please try it out.

The flipside being that you'll now have a bunch of extra logging on STDERR (this is the cause—we're logging to a target we never used before), but it should be easy to strip out of your build process.

**Comment by amarcu5** [comment] 2017-09-27 14:47
I'm now getting the error `Cannot read property 'u' of undefined`:

```
Skipping pass checkVariableReferences
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, exponent operator (**), async function, trailing comma in param list]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkMissingSuper
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, exponent operator (**), async function, trailing comma in param list]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkSideEffects
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, exponent operator (**), async function, trailing comma in param list]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass suspiciousCode
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, exponent operator (**), async function, trailing comma in param list]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkVars
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, exponent operator (**), async function, trailing comma in param list]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkRegExp
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, exponent operator (**), async function, trailing comma in param list]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass GlobalTypeInfo
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, computed property, exponent operator (**), extended object literal, for-of loop, generator, member declaration, template literal]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass NewTypeInference
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, computed property, exponent operator (**), extended object literal, for-of loop, generator, member declaration, template literal]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass inlineTypeAliases
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkAccessControls
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkGlobalNames
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass resolveTypes
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass inferTypes
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
Skipping pass checkTypes
factory features:  [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma]
compiler features: [block function, ES3 keywords as identifiers, getters, reserved words as properties, setters, string continuation, trailing comma, arrow function, binary literal, octal literal, class, computed property, extended object literal, for-of loop, generator, let declaration, member declaration, RegExp flag 'y', array pattern rest, rest parameter, spread expression, super, template literal, const declaration, destructuring, new.target, RegExp flag 'u', default parameter, modules]
{ Error: java.lang.RuntimeException: INTERNAL COMPILER ERROR. Please report this problem.  (TypeError) : Cannot read property 'u' of undefined   Node(NAME symbol): externs.zip//externs/es3.js:36:4 var symbol;   Parent(VAR): externs.zip//externs/es3.js:36:0 var symbol; 
    at EJ.fH [as $f] (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7902:22939)
    at EJ.iH [as ag] (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7902:23134)
    at EJ.eH (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:2284:48)
    at EJ.mH (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:626:19)
    at EJ (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:624:19)
    at UGb (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:5754:95)
    at _zc (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:4608:106)
    at aAc (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:5434:126)
    at lAc (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:2820:53)
    at xcc (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:2983:25)
    at ycc.zcc [as ng] (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7902:252693)
    at VKc (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7479:300)
    at WKc.XKc [as ng] (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7902:322932)
    at LKc (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:5797:146)
    at uGb (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:5309:121)
    at sHb.tHb [as gi] (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7902:156976)
    at FHb (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:4758:36)
    at uFb (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7272:235)
    at jfd (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:7514:358)
    at UJ (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:1803:29)
    at XJ (/usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:3133:44)
    at /usr/local/lib/node_modules/google-closure-compiler-js/jscomp.js:3334:46
    at module.exports (/usr/local/lib/node_modules/google-closure-compiler-js/compile.js:31:15)
    at ready (/usr/local/lib/node_modules/google-closure-compiler-js/cmd.js:107:18)
    at Promise.all.then.arr (/usr/local/lib/node_modules/google-closure-compiler-js/cmd.js:58:45)
    at <anonymous>
  '__java$exception': 
   { f: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        No: [Object],
        Oo: [Object],
        Po: [Function: hjb],
        '__elementTypeId$': 214,
        '__elementTypeCategory$': 0 ],
     e: 'INTERNAL COMPILER ERROR.\nPlease report this problem.\n\n(TypeError) : Cannot read property \'u\' of undefined\n  Node(NAME symbol): externs.zip//externs/es3.js:36:4\nvar symbol;\n  Parent(VAR): externs.zip//externs/es3.js:36:0\nvar symbol;\n',
     backingJsObject: [Circular] } }
```

**Comment by samthor** [comment] 2017-09-28 04:18
@amarcu5 what is the repro case? @philipwalton's case now builds fine.

**Comment by amarcu5** [comment] 2017-09-28 08:59
Reduced example:

```
const closureFlags = {
  jsCode: [{
    src: 'console.log(`foo`)',
    path: 'foo.js',
  }],
  languageIn: 'ECMASCRIPT_2017',
  languageOut: 'ECMASCRIPT_2017',
  compilationLevel: 'ADVANCED',
  warningLevel: 'VERBOSE',
  newTypeInf: true,
};
```

**Comment by concavelenz** [comment] 2017-12-01 18:35
@MatrixFrog

**Comment by MatrixFrog** [comment] 2017-12-08 22:06
It looks like this is fixed now (and this months release was published to npm successfully).

**Closed by MatrixFrog** 2017-12-08 22:06 UTC
